[package]
name = "sdgui"
version = "0.1.1"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3"
chrono = "0.4"
